### ISSUE TITLE
hidden sections in Collapsed Topics format display to students

### ISSUE THREAD

**Issue by phette23** [cca/moodle-styles#3]
Here's the student view of a course (LITPA-2000-9-WRLIT-2100-5-2021SP) with many hidden sections in a row:

<img width="949" alt="Screen Shot 2021-01-12 at 2 09 20 PM" src="https://user-images.githubusercontent.com/1024833/104380401-cdac6680-54df-11eb-9747-9172416f4ff4.png">

There's a `.hidden` class on the section `<li>` but it's overridden by another, more specific rule that forces it to display:

```css
li.section.hidden, .block.hidden, .block.invisible {
    visibility: visible;
    display: block
}
```

a bizarre contradiction in itself. We should still, to be safe, probably only override this behavior under the collapsed topics list of sections `ul.ctopics`.
