### ISSUE TITLE
To Do items are aligned right instead of left in Collapsed Topics

### ISSUE THREAD

**Issue by nchan31** [cca/moodle-styles#51]
With the update to 4.4, the list of to do items for activity completion appears as a dropdown and is aligned to the left in the updated "course sections" course format (previously "Topics").
![Image](https://github.com/user-attachments/assets/a4809531-58b1-4c59-8a31-ea6c7ae96bbb)

in Collapsed Topics, the list is aligned to the right:
![Image](https://github.com/user-attachments/assets/f9158a3d-9363-41be-bd63-1b61691e250f)

Other course formats align to the left as expected.

**Comment by phette23** [comment]
Looks like this comes down to this CSS rule:

```css
body.format-topcoll .ctopics .section .d-flex {
    flex-wrap: wrap;
    justify-content: space-between;
}
```

If you remove the `justify-content` property, text aligns to the left as you'd expect.
